# Blog info
title:          Nic's blog
description:    Yet another nerdy blog.
# The URL must be completed with the absolute path once in production
url:            
logo:           

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:  /:categories/:title/

# Owner info
owner:
    name:   Niccolò Olivieri
    avatar: profile-square.jpg
    bio:    Yet another boring nerd.
    email:  
    social:
        # Put only usernames
        twitter:        dotzweer
        facebook:       zweer
        github:         Zweer
        stackexchange:  
        linkedin:       
        instagram:      
        flickr:         
        tumblr:         
        # Google Plus id, include the '+'
        google_plus:    +NiccolòOlivieri

# Blog features
## Reading time of articles
readingTime:
    enabled:        true
    wordPerMinute:  200
## Comments
disqus:
    enabled:    true
    slug:       zweer
# Google - analytics and webmaster tools
google:
    analytics:  UA-40908812-1
    verify:     xVWjDgb14e3eZTNAL8g79JF4eHKw9AsigHLk9hLLh-A
# Gems
gems:
    - jekyll-sitemap

include:
    - .htaccess
exclude:
    - .bundle
    - .idea
    - .c9
    - .git
    - .sass-cache
    - _sass
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - gulpfile.js
    - bower.json
    - package.json
    - node_modules
    - "npm-debug.log*"
    - bower_components